import mongoose, { Schema, Document } from "mongoose";

// --- 1. STATE INTERFACE & SCHEMA (Temporary handshake storage) ---
export interface IAtprotoState extends Document {
  key: string; // The state session key generated by the SDK
  value: string; // JSON stringified NodeSavedState
  createdAt: Date;
}

const AtprotoStateSchema = new Schema<IAtprotoState>({
  key: { type: String, required: true, unique: true, index: true },
  value: { type: String, required: true },
  createdAt: { type: Date, default: Date.now, expires: 1800 }, // Auto-deletes records after 30 minutes (1800 seconds)
});

// --- 2. SESSION INTERFACE & SCHEMA (Long-lived cryptographic tokens) ---
export interface IAtprotoSession extends Document {
  key: string; // Usually the user's DID (e.g. did:plc:...)
  value: string; // JSON stringified NodeSavedSession
  updatedAt: Date;
}

const AtprotoSessionSchema = new Schema<IAtprotoSession>(
  {
    key: { type: String, required: true, unique: true, index: true },
    value: { type: String, required: true },
  },
  { timestamps: true },
);

// Avoid Next.js compilation re-definition errors during Hot Module Replacement (HMR)
export const AtprotoState =
  mongoose.models.AtprotoState ||
  mongoose.model<IAtprotoState>("AtprotoState", AtprotoStateSchema);
export const AtprotoSession =
  mongoose.models.AtprotoSession ||
  mongoose.model<IAtprotoSession>("AtprotoSession", AtprotoSessionSchema);
